# Generated by Django 4.1.7 on 2023-03-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('duration', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='package_profile/')),
                ('description', models.CharField(max_length=500)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
