# Generated by Django 4.1.7 on 2023-03-25 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='username',
        ),
    ]
