# Generated by Django 4.1.7 on 2023-04-04 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_registration_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_name', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('journey_date', models.DateField()),
                ('total_people', models.IntegerField()),
                ('pickup_point', models.CharField(choices=[('ahmedabad', 'AHMEDABAD'), ('surat', 'SURAT'), ('rajkot', 'RAJKOT'), ('baroda', 'BARODA'), ('bhavnagar', 'BHAVNAGAR'), ('bhuj', 'BHUJ')], max_length=50)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='services.package')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
